// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ES3JuOlzQBz6g9OUbpiVkCo1ySKZaMk',
    appId: '1:996265387274:web:58fc6196315096825886f3',
    messagingSenderId: '996265387274',
    projectId: 'sihproject-8c96a',
    authDomain: 'sihproject-8c96a.firebaseapp.com',
    storageBucket: 'sihproject-8c96a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHOEuxeIuLszwKBcgV6hfmhdaxMBMeMCs',
    appId: '1:553626694568:android:5ebe56ba6aca9d1ff7a39d',
    messagingSenderId: '553626694568',
    projectId: 'sihproject-6a1a4',
    storageBucket: 'sihproject-6a1a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKByDVd2jMXv4sHM6VlDYh4Arr33N9Xk',
    appId: '1:996265387274:ios:d047a1cda0c700345886f3',
    messagingSenderId: '996265387274',
    projectId: 'sihproject-8c96a',
    storageBucket: 'sihproject-8c96a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKByDVd2jMXv4sHM6VlDYh4Arr33N9Xk',
    appId: '1:996265387274:ios:d047a1cda0c700345886f3',
    messagingSenderId: '996265387274',
    projectId: 'sihproject-8c96a',
    storageBucket: 'sihproject-8c96a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ES3JuOlzQBz6g9OUbpiVkCo1ySKZaMk',
    appId: '1:996265387274:web:a9c1e54fbdd866c85886f3',
    messagingSenderId: '996265387274',
    projectId: 'sihproject-8c96a',
    authDomain: 'sihproject-8c96a.firebaseapp.com',
    storageBucket: 'sihproject-8c96a.firebasestorage.app',
  );
}